# Generated by Django 2.1.5 on 2019-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20190121_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecont',
            name='figuredob',
            field=models.CharField(default='dob', max_length=200),
            preserve_default=False,
        ),
    ]
