# Generated by Django 2.1.5 on 2019-01-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_languagecont_figuredob'),
    ]

    operations = [
        migrations.CreateModel(
            name='example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=200)),
                ('examOne', models.TextField()),
                ('examTwo', models.TextField()),
                ('examThree', models.TextField()),
            ],
        ),
    ]
