# Generated by Django 2.1.5 on 2019-01-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='popeditor1',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='example',
            name='popeditor1link',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='example',
            name='popeditor2',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='example',
            name='popeditor2link',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='example',
            name='popeditor3',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='example',
            name='popeditor3link',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='example',
            name='popeditor4',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='example',
            name='popeditor4link',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='example',
            name='popeditors',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
