# Generated by Django 2.1.5 on 2019-01-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20190123_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='popeditors',
            field=models.CharField(default='Popular Editors', max_length=200),
        ),
    ]
