# Generated by Django 2.1.5 on 2019-01-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20190123_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='popeditor2link',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
