# Generated by Django 2.1.5 on 2019-01-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about1', models.TextField(default=' ')),
                ('about2', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEO', models.CharField(default=' ', max_length=200)),
                ('email', models.CharField(default=' ', max_length=200)),
                ('telephone', models.CharField(default=' ', max_length=200)),
            ],
        ),
    ]
